package migrate

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

// MigrationResult holds the migrated values and any warnings
type MigrationResult struct {
	Values   *NewValues
	Warnings []Warning
}

// Migrate transforms legacy values to new values
func Migrate(legacy *LegacyValues) (*MigrationResult, error) {
	result := &MigrationResult{
		Values:   &NewValues{},
		Warnings: []Warning{},
	}

	// 1. Direct field mappings
	mapDirectFields(legacy, result)

	// 2. Ingress transformation
	mapIngress(legacy, result)

	// 3. Storage transformation
	mapStorage(legacy, result)

	// 4. Database transformation
	mapDatabase(legacy, result)

	// 5. Redis transformation
	mapRedis(legacy, result)

	// 6. Component mappings
	mapCore(legacy, result)
	mapPortal(legacy, result)
	mapRegistry(legacy, result)
	mapJobservice(legacy, result)
	mapExporter(legacy, result)
	mapTrivy(legacy, result)

	// 7. Metrics transformation
	mapMetrics(legacy, result)

	// 8. Check for unsupported features
	checkUnsupportedFeatures(legacy, &result.Warnings)

	return result, nil
}

// MigrateFromYAML parses legacy YAML and returns migrated values
func MigrateFromYAML(data []byte) (*MigrationResult, error) {
	var legacy LegacyValues
	if err := yaml.Unmarshal(data, &legacy); err != nil {
		return nil, fmt.Errorf("failed to parse legacy values: %w", err)
	}

	return Migrate(&legacy)
}

// ToYAML converts the new values to YAML bytes
func (r *MigrationResult) ToYAML() ([]byte, error) {
	return yaml.Marshal(r.Values)
}

// ToYAMLWithHeader converts the new values to YAML with a header comment
func (r *MigrationResult) ToYAMLWithHeader(sourceFile string) ([]byte, error) {
	output, err := yaml.Marshal(r.Values)
	if err != nil {
		return nil, err
	}

	header := fmt.Sprintf(`# ============================================================================
# MIGRATED VALUES - Generated by harbor-migrate
# ============================================================================
# Original file: %s
# Review all warnings above before using this file.
# ============================================================================

`, sourceFile)

	return append([]byte(header), output...), nil
}
