apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-core
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "core") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 8001
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "core") | nindent 4 }}
