{{- if .Values.jobservice.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harbor.serviceAccountName" (dict "root" . "component" "jobservice" "serviceAccount" .Values.jobservice.serviceAccount) }}
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "jobservice") | nindent 4 }}
  {{- with .Values.jobservice.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
