apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-jobservice
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "jobservice") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-jobservice
      port: 80
      targetPort: {{ include "harbor.jobservice.port" . }}
      protocol: TCP
    - name: {{ include "harbor.metrics.portName" . | quote }}
      port: {{ include "harbor.metrics.port" . }}
      protocol: TCP
      targetPort: {{ include "harbor.metrics.port" . }}
  selector:
    {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "jobservice") | nindent 4 }}
