{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "harbor.jobservice" .)) | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-jobservice
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "jobservice") | nindent 4 }}
type: Opaque
data:
  {{- if .Values.jobservice.secret }}
  {{- include "harbor.toEnvVars" (dict "values" .Values.jobservice.secret "prefix" "" "isSecret" true) | nindent 2 }}
  {{- end }}
  # Placeholder to ensure secret is always created
  _PLACEHOLDER: {{ "placeholder" | b64enc | quote }}
  {{- if not .Values.jobservice.existingSecret }}
  JOBSERVICE_SECRET: {{ .Values.jobservice.secret | default (include "harbor.secretKeyHelper" (dict "key" "JOBSERVICE_SECRET" "data" ($existingSecret.data | default dict))) | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
  {{- if not .Values.registry.credentials.existingSecret }}
  REGISTRY_CREDENTIAL_PASSWORD: {{ .Values.registry.credentials.password | b64enc | quote }}
  {{- end }}
  {{- template "harbor.trace.jaeger.password" . }}
