{{- if .Values.registry.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "harbor.fullname" . }}-registry
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "registry") | nindent 4 }}
spec:
  {{- if .Values.registry.pdb.minAvailable }}
  minAvailable: {{ .Values.registry.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.registry.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.registry.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "registry") | nindent 6 }}
{{- end }}
