apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor.registry.name" . }}
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "registry") | nindent 4 }}
spec:
  replicas: {{ .Values.registry.replicas }}
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "registry") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/registry.configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/registry.secret.yaml") . | sha256sum }}
        {{- with .Values.registry.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "registry") | nindent 8 }}
        {{- with .Values.registry.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "harbor.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "harbor.serviceAccountName" (dict "root" . "component" "registry" "serviceAccount" .Values.registry.serviceAccount) }}
      securityContext:
        {{- toYaml .Values.registry.podSecurityContext | nindent 8 }}
      containers:
        - name: registryctl
          securityContext:
            {{- toYaml .Values.registry.securityContext | nindent 12 }}
          image: {{ include "harbor.image" (dict "imageRoot" .Values.registry.controller.image "global" .Values.image "chart" .Chart) }}
          imagePullPolicy: {{ include "harbor.imagePullPolicy" . }}
          ports:
            - name: ctl
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "harbor.fullname" . }}-registryctl
            - secretRef:
                name: {{ include "harbor.fullname" . }}-registry
            - secretRef:
                name: {{ include "harbor.fullname" . }}-registryctl
          env:
            {{- if .Values.registry.existingSecret }}
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.registry.existingSecret }}
                  key: {{ .Values.registry.existingSecretKey }}
            {{- end }}
            - name: CORE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "harbor.core" .) .Values.core.existingSecret }}
                  key: secret
            - name: JOBSERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "harbor.jobservice" .) .Values.jobservice.existingSecret }}
                  {{- if .Values.jobservice.existingSecret }}
                  key: {{ .Values.jobservice.existingSecretKey }}
                  {{- else }}
                  key: JOBSERVICE_SECRET
                  {{- end }}
            {{- if has "registry" .Values.proxy.components }}
            - name: HTTP_PROXY
              value: "{{ .Values.proxy.httpProxy }}"
            - name: HTTPS_PROXY
              value: "{{ .Values.proxy.httpsProxy }}"
            - name: NO_PROXY
              value: "{{ template "harbor.noProxy" . }}"
            {{- end }}

            {{- with .Values.registry.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: ctl
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: ctl
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
          volumeMounts:
            {{- if eq .Values.registry.storage.type "filesystem" }}
            - name: storage
              mountPath: {{ .Values.registry.storage.filesystem.rootdirectory | default "/storage" }}
            {{- end }}
            - name: registry-config
              mountPath: /etc/registry/config.yml
              subPath: config.yml
            - name: registry-config
              mountPath: /etc/registryctl/config.yml
              subPath: ctl-config.yml

      volumes:
        - name: registry-htpasswd
          secret:
            {{- if not .Values.registry.credentials.existingSecret }}
            secretName: {{ include "harbor.registry.name" . }}-htpasswd
            {{ else }}
            secretName: {{ .Values.registry.credentials.existingSecret }}
            {{- end }}
            items:
              - key: REGISTRY_HTPASSWD
                path: passwd
        - name: registry-config
          configMap:
            name: {{ include "harbor.registry.name" . }}
        - name: registry-data
        {{- if and .Values.registry.persistence.enabled (eq .Values.registry.storage.type "filesystem") }}
          persistentVolumeClaim:
            claimName: {{ .Values.registry.persistence.existingClaim | default (include "harbor.registry.name" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if eq .Values.registry.storage.type "filesystem" }}
        - name: storage
          {{- if .Values.registry.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.registry.persistence.existingClaim }}
          {{- else if .Values.registry.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "harbor.registry.name" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if and (eq .Values.registry.storage.type "gcs") .Values.registry.storage.gcs.keyfile }}
        - name: gcs-key
          secret:
            secretName: {{ include "harbor.fullname" . }}-registry-gcs
        {{- end }}
      {{- with .Values.registry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
