apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-registry
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "registry") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-registry
      port: {{ include "harbor.registry.port" . }}
      targetPort: {{ include "harbor.registry.port" . }}
      protocol: TCP
    - name: http-controller
      port: {{ include "harbor.portal.service.port" . }}
      targetPort: {{ include "harbor.portal.service.port" . }}
      protocol: TCP
    - name: {{ include "harbor.metrics.portName" . | quote }}
      port: {{ include "harbor.metrics.port" . }}
      targetPort: {{ include "harbor.metrics.port" . }}
      protocol: TCP
  selector:
    {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "registry") | nindent 4 }}
