apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-registryctl
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  {{- template "harbor.trace.jaeger.password" . }}
