apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor.fullname" . }}-registryctl
  labels:
{{ include "harbor.labels" . | indent 4 }}
data:
  {{- template "harbor.trace.envs.registryctl" . }}
