apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-registry
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "registry") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
    - name: ctl
      port: 8080
      targetPort: ctl
      protocol: TCP
    - name: metrics
      port: 5001
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "registry") | nindent 4 }}
